config/routes.rb
BatchManager::Engine.routes.draw do

  root :to => "batches#index"

  resources :batches do
    member do
      get :exec
      get :log
      get :async_read_log
      get :remove_log
    end
  end

end

app/controllers/batch_manager/application_controller.rb
require 'socket'

module BatchManager
  class ApplicationController < ActionController::Base
    helper_method :resque_supported?, :local_resque_worker?, :resque_worker_hostname

    def resque_supported?
      begin
        require 'resque'
        defined?(Resque) && resque_worker
      rescue LoadError
        false
      end
    end

    def local_resque_worker?
      Socket.gethostname == resque_worker_hostname
    end

    def resque_worker_hostname
      resque_worker.id.split(':')[0]
    end

    private

    def resque_worker
      @resque_worker ||= begin
        workers = Resque.workers.select do |worker|
          queue_names = worker.id.split(':')[-1].split(',')
          queue_names.include?(BatchManager::ExecBatchWorker.queue_name) || queue_names.include?("*")
        end
        workers.first
      end
    end
  end
end

app/controllers/batch_manager/batches_controller.rb
require 'generators/batch/batch_generator'

module BatchManager
  class BatchesController < ApplicationController
    include BatchManager::Utils
    before_filter :retain_batch_params, :except => [:index, :new, :create]
    helper_method :escape_batch_name

    def index
      @details = BatchManager::Monitor.details
    end

    def new
      template = File.read(File.join(Rails::Generators::BatchGenerator.source_root, "batch.rb"))
      @content = ERB.new(template).result(binding)
    end

    def create
      batch_name = params[:batch_name]
      if batch_name.blank?
        flash[:error] = "Please input the batch name."
        redirect_to(new_batch_url) and return 
      end
      file_path = File.join(BatchManager.batch_dir, batch_name)
      file_path << ".rb" unless file_path.end_with?(".rb")
      FileUtils.mkdir_p(File.dirname(file_path)) if batch_name.include?("/")
      File.open(file_path, "w") { |f| f << params[:content] }
      redirect_to(batches_url, :notice => "#{batch_name} created.")
    end

    def edit
      @content = File.read(batch_full_path(@batch_name))
    end

    def update
      File.open(batch_full_path(@batch_name), "w") { |f| f << params[:content] }
      redirect_to(batches_url, :notice => "#{@batch_name} updated.")
    end

    def exec
      if resque_supported?
        Resque.enqueue(BatchManager::ExecBatchWorker, @batch_name, :wet => @wet)
        if local_resque_worker?
          redirect_to(batches_url, :notice => "(#{@batch_name}) Task added to the remote resque worker.")
        else
          redirect_to(batches_url, :notice => "(#{@batch_name}) Task added to the remote resque worker.")
        end
      else
        BatchManager::Executor.exec(@batch_name, :wet => @wet)
        redirect_to(batches_url)
      end
    end

    def log
      @offset = log_file.size
      @content = log_file.read
    end

    def async_read_log
      log_file.seek(params[:offset].to_i) if params[:offset].present?
      render :json => {:content => log_file.read, :offset => log_file.size}
    end

    def remove_log
      FileUtils.rm(BatchManager::Logger.log_file_path(@batch_name, @wet))
      redirect_to(batches_url, :notice => "Log removed.")
    end

    def escape_batch_name(name)
      name.gsub("/", "|")
    end

    def unescape_batch_name(name)
      name.gsub("|", "/")
    end

    private

    def retain_batch_params
      @batch_name = unescape_batch_name(params[:id])
      @wet = params[:wet]
    end

    def log_file
      5.times do
        begin
          @log_file ||= File.open(BatchManager::Logger.log_file_path(@batch_name, @wet), 'r')
          return @log_file
        rescue
          sleep 2
          retry
        end
      end
    end
  end
end

app/views/batch_manager/batches/_form_content.html.erb
<%= hidden_field_tag :content, @content, :id => "content" %>
<div id="editor"><%= @content %></div>
<div class="group" style="margin-top:15px;">
  <div style="float:left;"><%= submit_tag "Save", :class => "btn info large" %></div>
  <div style="margin-left:15px;float:left;padding-top:6px;">
    <%= link_to "Cancel", batches_url, :class => "cancel" %>
  </div>
</div>

app/views/batch_manager/batches/edit.html.erb
<%= javascript_include_tag "batch_manager/editor" %>

<div class="group title">
  <h2 style="float:left;">Edit Batch</h2>
  <div class="label" style="float:left;margin-left:25px;"><%= @batch_name %></div>
</div>

<%= form_tag batch_url(escape_batch_name(@batch_name)), :method => :put do %>
  <%= render "form_content" %>
<% end %>

app/views/batch_manager/batches/exec.html.erb
<script>
  function read_log() {
    offset = $("#offset").val();
    $.get('<%= async_read_log_batches_url(:batch_name => @batch_name, :wet => @wet) %>' + '&offset=' + offset, function(data) {
      $("#log_box").val($("#log_box").val() + data.content);
      $("#offset").val(data.offset);
      scrollLogBoxDown();
    });
  }
  function scrollLogBoxDown() {
    var logBox = $('#log_box');
    logBox.scrollTop(logBox[0].scrollHeight - logBox.height());
  }
  $(function() {
    setInterval(read_log, 1000);
  });
</script>

<h2><%= @batch_name %> <%= "WET RUN" if @wet %> Executing!<h2>

<%= text_area_tag :log, nil, :id => "log_box" %>
<%= hidden_field_tag :offset, @offset, :id => :offset %>

app/views/batch_manager/batches/index.html.erb
<div class="group title">
  <h2 style="float:left;">Batches</h2>
  <div style="float:right;text-align:right;">
    <% if resque_supported? %>
      <% if local_resque_worker? %>
        <div class="label info">Resque worker found</div>
      <% else %>
        <div class="label info">Resque worker found on <%= resque_worker_hostname %></div>
      <% end %>
    <% else %>
      <div class="label warn">Resque or Resque worker not found</div>
    <% end %>
  </div>
</div>
<table>
  <tr>
    <th>Managed?</th>
    <th>Name</th>
    <th>Ran/Limit</th>
    <th>Last run at</th>
    <th>Created at</th>
    <th>Log</th>
    <th></th>
  </tr>
  <% @details.each do |status| %>
    <% schema_batch = status.schema_batch %>
    <tr>
      <td><%= status.managed?? "Yes" : "" %></td>
      <td style="word-break:break-all;"><%= status.name %></td>
      <td style="text-align:right;"><%= schema_batch.try(:ran_times).to_i %><span class="divider">/</span><%= status.times_limit || 0 %></td>
      <td style="text-align:center;white-space:nowrap;">
        <% if last_ran_at = schema_batch.try(:last_ran_at) %>
          <%= last_ran_at.strftime('%Y-%m-%d %H:%M:%S') %>
        <% end %>
      </td>
      <td style="text-align:center;white-space:nowrap;"><%= status.created_at.strftime('%Y-%m-%d %H:%M:%S') if status.created_at %></td>
      <td style="text-align:center;white-space:nowrap;">
        <% if File.exist?(BatchManager::Logger.log_file_path(status.name)) %>
          <%= link_to "DRY", log_batch_url(escape_batch_name(status.name)), :class => "btn info" %>
          <%= link_to "X", remove_log_batch_url(escape_batch_name(status.name)), :class => "btn danger", :onclick => "return confirm('Are you sure?')" %>
        <% end %>
        <% if File.exist?(BatchManager::Logger.log_file_path(status.name, true)) %>
          <%= link_to "WET", log_batch_url(escape_batch_name(status.name), :wet => true), :class => "btn info" %>
          <%= link_to "X", remove_log_batch_url(escape_batch_name(status.name), :wet => true), :class => "btn danger", :onclick => "return confirm('Are you sure?')" %>
        <% end %>
      </td>
      <td style="text-align:center;white-space:nowrap;">
        <%= link_to "EDIT", edit_batch_url(escape_batch_name(status.name)), :class => "btn info" %>
        <% if status.managed? %>
          <%= link_to "DRY RUN", exec_batch_url(escape_batch_name(status.name)), :class => "btn info" %>
          <% if status.can_run? %>
            <%= link_to "WET RUN", exec_batch_url(escape_batch_name(status.name), :wet => true), :class => "btn danger", :onclick => "return confirm('Are you sure?')" %>
          <% else %>
            <%= link_to "WET RUN", "#", :class => "btn disabled", :onclick => "return false" %>
          <% end %>
        <% else %>
          <%= link_to "DRY RUN", "#", :class => "btn disabled", :onclick => "return false" %>
          <%= link_to "WET RUN", "#", :class => "btn disabled", :onclick => "return false" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/batch_manager/batches/log.html.erb
<% if params[:refresh] %>
<script>
  function read_log() {
    offset = $("#offset").val();
    $.get('<%= async_read_log_batch_url(escape_batch_name(@batch_name), :wet => @wet, 1 => 1) %>' + '&offset=' + offset, function(data) {
      $("#log_box").val($("#log_box").val() + data.content);
      $("#offset").val(data.offset);
      scrollLogBoxDown();
    });
  }
  function scrollLogBoxDown() {
    var logBox = $('#log_box');
    logBox.scrollTop(logBox[0].scrollHeight - logBox.height());
  }
  $(function() {
    setInterval(read_log, 2000);
  });
</script>
<% end %>

<div class="group title">
  <h2><%= @batch_name %></h2>
</div>

<%= text_area_tag :log, @content, :id => "log_box" %>
<%= hidden_field_tag :offset, @offset, :id => :offset %>

<div style="margin-top:15px;">
  <%= link_to "Back to list", batches_url, :class => "btn info large" %>
</div>

app/views/batch_manager/batches/new.html.erb
<%= javascript_include_tag "batch_manager/editor" %>

<%= form_tag batches_url do %>
  <div class="group title">
    <h2 style="float:left;">New Batch</h2>
    <div class="new_batch" style="float:left;margin-left:25px;"><%= text_field_tag :batch_name, nil, :placeholder => "Batch name here..." %></div>
  </div>
  <%= render "form_content" %>
<% end %>

app/views/layouts/batch_manager/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BatchManager</title>
  <%= stylesheet_link_tag    "batch_manager/application", :media => "all" %>
  <%= javascript_include_tag "batch_manager/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="inner">
      <h1><%= link_to "BatchManager", batches_url %></h1>
      <div class="new_link"><%= link_to "NEW BATCH", new_batch_url %></div>
    </div>
  </header>

  <div id="wrapper">
    <div class="group">
      <% if flash[:notice] %>
        <div class="alert notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:error] %>
        <div class="alert error"><%= flash[:error] %></div>
      <% end %>
    </div>
    <%= yield %>
  </div>

  <footer>
    <p><a href="https://github.com/cctiger36/batch_manager">BatchManager</a> VERSION <%= BatchManager::VERSION %></p>
  </footer>

</body>
</html>